name: Deploy Lambda Code Only

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::220217777401:role/GitHubActions-NijisanjiMusic
          aws-region: ap-northeast-1

      - name: Install Lambda Dependencies
        working-directory: ./lambdaFunctions
        run: npm install --omit=dev

      - name: Create Deployment Package
        working-directory: ./lambdaFunctions
        run: zip -r ../deployment-package.zip . -x ".git/*" ".github/*"

      - name: Upload package to S3
        run: aws s3 cp ../deployment-package.zip s3://${{ secrets.S3_DEPLOYMENT_BUCKET }}/lambda-packages/getLiverYouTube-${{ github.sha }}.zip

      - name: Deploy to Lambda referencing S3 object
        run: >
          aws lambda update-function-code
          --function-name getLiverYouTube
          --s3-bucket ${{ secrets.S3_DEPLOYMENT_BUCKET }}
          --s3-key lambda-packages/getLiverYouTube-${{ github.sha }}.zip
