name: Deploy Sanity Studio on Change

on:
  workflow_dispatch:
    inputs:
      exampleInput:
        description: "Sanity.ioへのデプロイ"
        required: false
        default: ""
  push:
    branches:
      - main
    paths:
      - "sanity/**"
      - "app/studio/**"

jobs:
  deploy-sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Sanity CLI and dependencies
        run: npm install
        working-directory: .

      - name: Deploy Sanity Studio
        run: npx sanity deploy --non-interactive
        working-directory: .
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
          SANITY_STUDIO_PROJECT_ID: ${{ secrets.SANITY_STUDIO_PROJECT_ID }}
          SANITY_STUDIO_DATASET: ${{ secrets.SANITY_STUDIO_DATASET }}
